<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

| **Term**   | **Brief description**           |
|------------|---------------------------------|
| Subsetting | To select                       |
| Indexing   | To select one index             |
| Slicing    | To select a range of index      |
| Masking    | filtering data using true/false |

# Exercise 2

In [19]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
x = np_array_2d
x[:,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [ ]:
x = np_array_2d.astype(int) # can only be performed on number

In [21]:
x[:,0].astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [35]:
a = x[:,0].astype(int)
b = a%2
b

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [36]:
my_mask = b >= 1
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [39]:
a[my_mask]

array([1, 3, 5, 7, 9])

In [46]:
x[my_mask][:,1] 

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [48]:
x[my_mask, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')