<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [4]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [5]:
x[0]

'a1'

In [6]:
x[7]

'h8'

In [7]:
x[-2]

'i9'

In [9]:
x[0:4] # 4-0

array(['a1', 'b2', 'c3', 'd4'], dtype='<U3')

In [8]:
x[1:6] # 6-1

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [11]:
x[1:6:2] #every other one of 6-1

array(['b2', 'd4', 'f6'], dtype='<U3')

In [12]:
x[6:] # index 6 to end

array(['g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [13]:
len(x) # no of elements

10

In [15]:
x[:4]

array(['a1', 'b2', 'c3', 'd4'], dtype='<U3')

In [16]:
x[5:2:-1] # index 5 to 3 in reverse

array(['f6', 'e5', 'd4'], dtype='<U3')

In [17]:
x[2:5:-1] # need to reverse to code from index 5 to 3

array([], dtype='<U3')

In [20]:
x[2:7] # total of 7-2 elements

array(['c3', 'd4', 'e5', 'f6', 'g7'], dtype='<U3')

In [21]:
x[7:2:-1] # reverse of index 7 to 5

array(['h8', 'g7', 'f6', 'e5', 'd4'], dtype='<U3')

In [18]:
x[7:2:-2] # every other one of reverse of index 7 to 5

array(['h8', 'f6', 'd4'], dtype='<U3')

In [22]:
x[7:2:-3] # every other 3 in reverse

array(['h8', 'e5'], dtype='<U3')

In [23]:
x[7:2:-4] # every other 4 in reverse

array(['h8', 'd4'], dtype='<U3')

In [24]:
x[7:2:-5] # every other 5 in reverse

array(['h8'], dtype='<U3')

In [28]:
x[7:2:-100] # - more than 5: will js display index 7

array(['h8'], dtype='<U3')

In [29]:
x[::-1] # reverse list

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

In [30]:
x[::-2] # every other one in reverse

array(['j10', 'h8', 'f6', 'd4', 'b2'], dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [34]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask # masking = filtering, only for np array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [36]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = np_array > 5
x

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [37]:
np_array[x]

array([ 6,  7,  8,  9, 10])

In [38]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [39]:
np_array[~(np_array > 5)]                 # elements <=5

array([1, 2, 3, 4, 5])

In [40]:
np_array[(np_array > 3) & (np_array < 8)]  # '&' means 'AND'
# 3 < x < 8

array([4, 5, 6, 7])

In [41]:
np_array[(np_array < 3) | (np_array > 8)]  # '|' means 'OR'
# x < 3 or x > 8

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [42]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [43]:
py_list_2d[2]

[3, 'C']

In [44]:
np_array_2d[5]

array(['6', 'F'], dtype='<U21')

In [50]:
py_list_2d[2][0] # OMIT sec element at index 2

3

In [46]:
py_list_2d[0][2] # out of range: index 0

IndexError: list index out of range

In [54]:
np_array_2d[2,0] # OMIT sec element at index 2 

'3'

In [55]:
py_list_2d[:3] # first 3 elements

[[1, 'A'], [2, 'B'], [3, 'C']]

In [56]:
np_array_2d[:3] # array includes type of data

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [57]:
py_list_2d[:3][0] # py list only shows first element

[1, 'A']

In [58]:
np_array_2d[:3, 0] # array can display first 3 elements 

array(['1', '2', '3'], dtype='<U21')

In [59]:
py_list_2d[3:6][0] # first element in from index 3 to index 6

[4, 'D']

In [61]:
np_array_2d[3:6,0]

array(['4', '5', '6'], dtype='<U21')

In [62]:
np_array_2d[:,0] # display everything, omit letter

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [64]:
x = [1,3]*8
x

[1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3]

In [65]:
x = [1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [66]:
x = [1] # short cut
x += [2]
x += [3]
x += [4]
x

[1, 2, 3, 4]

In [68]:
x=[1] # runs faster
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [69]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [70]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [71]:
x=[1, 2, 3]
x.append([4, 5, 6]) # keep the lists separate?
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [82]:
a = (1, 2, 3) # definition
a

(1, 2, 3)

In [83]:
a[0] # access data

1

In [77]:
a.extend([4, 5, 6]) # will not work

AttributeError: 'tuple' object has no attribute 'extend'

In [84]:
a[0]= -1 # will not work
a[0]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [86]:
x = [1 , 2, 3]

y=x.copy()
z=x.copy()
y

[1, 2, 3]

In [88]:
z

[1, 2, 3]